services:
  python:
    image: tugboatqa/debian
    default: true
    commands:
      init: 
        - apt-get update && apt-get install python3 python3-pip python3-venv
        - python3 -m venv mysite/env
        - . mysite/env/bin/activate
        - pip3 install wagtail
        - wagtail start mysite mysite
        - cd mysite && pip3 install -r requirements.txt
        - cd mysite && python3 manage.py migrate
        # Create the admin user. The password could also be 
        # stored as a Tugboat environment variable.
        - cd mysite && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'root@localhost', 'tugboat')" | python3 manage.py shell
        # Cleanup to reduce disk space
        - apt-get clean
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        
      # start:
        # Run on the default Tugboat port. 
        # cd mysite && python3 manage.py runserver 0.0.0.0:80 &

# Optionally install a redis cache.
  redis:
    image: tugboatqa/redis
    commands:
      init: 
        - apt-get update && apt-get install django-redis
