services:
  python:
    image: tugboatqa/debian
    commands:
      init: 
        - apt-get update && apt-get install python3 python3-pip python3-venv
        - python3 -m venv mysite/env
        - . mysite/env/bin/activate
        - pip3 install wagtail
        - wagtail start mysite mysite
        - cd mysite && pip3 install -r requirements.txt
        - cd mysite && python3 manage.py migrate
        # Need help here since this is an interactive command. NOT python manage.py createsuperuser
        - cd mysite && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'root@localhost', 'tugboat')" | python3 manage.py shell
        # Cleanup
        - apt-get clean
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        
      # start:
        # cd mysite && python3 manage.py runserver ${TUGBOAT_DEFAULT_SERVICE_URL}:80 &
