services:
  python:
    image: tugboatqa/debian
    commands:
      init: 
        - apt-get update && apt-get install python3 python3-pip python3-venv
        - python3 -m venv mysite/env
        - source mysite/env/bin/activate
        - pip install wagtail
        - wagtail start mysite mysite
        - cd mysite && pip install -r requirements.txt
        - python manage.py migrate
        # Need help here since this is an interactive command. NOT python manage.py createsuperuser
        - echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'root@localhost', 'tugboat')" | python manage.py shell
        
      start:
        - python manage.py runserver
